module.exports = [
  {
    id: 1,
    item_name: "Salary",
    amount: 2500,
    date: "2024-02-01",
    from: "Employer A",
    category: "Income",
    transactionType: "deposit",
  },
  {
    id: 2,
    item_name: "Rent",
    amount: 1000,
    date: "2024-02-03",
    from: "Landlord",
    category: "Housing",
    transactionType: "withdrawal",
  },
  {
    id: 3,
    item_name: "Groceries",
    amount: 200,
    date: "2024-02-05",
    from: "Grocery Store",
    category: "Food",
    transactionType: "withdrawal",
  },
  {
    id: 4,
    item_name: "Investment Dividend",
    amount: 300,
    date: "2024-02-07",
    from: "Investment Firm",
    category: "Investment",
    transactionType: "deposit",
  },
  {
    id: 5,
    item_name: "Utilities",
    amount: 150,
    date: "2024-02-10",
    from: "Utility Company",
    category: "Bills",
    transactionType: "withdrawal",
  },
  {
    id: 6,
    item_name: "Freelance Work",
    amount: 800,
    date: "2024-02-15",
    from: "Client B",
    category: "Income",
    transactionType: "deposit",
  },
  {
    id: 7,
    item_name: "Clothing",
    amount: 80,
    date: "2024-02-18",
    from: "Fashion Store",
    category: "Shopping",
    transactionType: "withdrawal",
  },
  {
    id: 8,
    item_name: "Bonus",
    amount: 500,
    date: "2024-02-19",
    from: "Company X",
    category: "Income",
    transactionType: "deposit",
  },
  {
    id: 9,
    item_name: "Internet Bill",
    amount: 70,
    date: "2024-02-21",
    from: "Internet Provider",
    category: "Bills",
    transactionType: "withdrawal",
  },
  {
    id: 10,
    item_name: "Savings Deposit",
    amount: 1000,
    date: "2024-02-28",
    from: "Personal Savings",
    category: "Savings",
    transactionType: "deposit",
  },
];
